# Generated by Django 3.2.9 on 2021-11-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('nik', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default=1, max_length=15)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('provinsi', models.CharField(blank=True, max_length=50)),
                ('staf', models.CharField(choices=[('1', 'Tetap'), ('3', 'Percobaan'), ('3', 'Harian'), ('2', 'Kontrak')], max_length=15)),
            ],
        ),
    ]
