# Generated by Django 3.2.9 on 2021-11-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20211113_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='staf',
            field=models.CharField(choices=[('3', 'Percobaan'), ('1', 'Tetap'), ('2', 'Kontrak'), ('3', 'Harian')], max_length=15),
        ),
    ]
