# Generated by Django 3.2.9 on 2021-11-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20211113_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='gender',
            field=models.CharField(choices=[('2', 'Female'), ('1', 'Male')], default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='staf',
            field=models.CharField(choices=[('3', 'Harian'), ('2', 'Kontrak'), ('3', 'Percobaan'), ('1', 'Tetap')], max_length=15),
        ),
    ]
