# Generated by Django 3.2.9 on 2021-11-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20211113_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='gender',
            field=models.CharField(choices=[(1, 'Pria'), (2, 'Wanita')], default=1, max_length=15),
        ),
    ]
