# Generated by Django 3.2.9 on 2021-11-16 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_employeemodel_golongan'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='bagian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.bagianmodel'),
        ),
    ]
