# Generated by Django 3.2.9 on 2021-11-17 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20211117_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='bagian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.bagianmodel'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='golongan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.golonganmodel'),
        ),
    ]
