# Generated by Django 3.2.9 on 2021-11-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20211117_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='gender',
            field=models.CharField(choices=[('1', 'Pria'), ('2', 'Wanita')], default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='staf',
            field=models.CharField(choices=[('1', 'Tetap'), ('2', 'Kontrak'), ('3', 'Percobaan'), ('4', 'Harian')], max_length=15),
        ),
    ]
