# Generated by Django 3.2.9 on 2021-11-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20211117_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='staf',
            field=models.CharField(choices=[('0', '--default--'), ('1', 'Tetap'), ('2', 'Kontrak'), ('3', 'Percobaan'), ('4', 'Harian')], default='0', max_length=15),
        ),
    ]
