# Generated by Django 3.2.9 on 2021-11-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('2', 'ReadWrite'), ('3', 'Full'), ('1', 'Read')], default=1, max_length=10),
        ),
    ]
