# Generated by Django 3.2.9 on 2021-11-11 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0002_alter_contact_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('1', 'Read'), ('2', 'ReadWrite'), ('3', 'Full')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='userowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
