# Generated by Django 3.2.9 on 2021-11-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20211112_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='nohp',
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('3', 'Full'), ('2', 'ReadWrite'), ('1', 'Read')], default=1, max_length=10),
        ),
    ]
