# Generated by Django 3.2.9 on 2021-11-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20211112_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('2', 'ReadWrite'), ('1', 'Read'), ('3', 'Full')], default=1, max_length=10),
        ),
    ]
