# Generated by Django 3.2.9 on 2021-11-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20211113_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('3', 'Full'), ('2', 'ReadWrite'), ('1', 'Read')], max_length=15),
        ),
    ]
