# Generated by Django 3.2.9 on 2021-11-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_auto_20211113_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('2', 'ReadWrite'), ('1', 'Read'), ('3', 'Full')], max_length=15),
        ),
    ]
