# Generated by Django 3.2.9 on 2021-11-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_alter_contact_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='role',
        ),
    ]
